In [187]:
#0.如何计算两个数组之间的欧氏距离？
import numpy as np
a = np.array([1,2,3])
b = np.array([3,2,1])
# M 1
def Dis(a,b):
    dis = np.sqrt(np.sum(np.square(a - b)))
    return dis
Dis(a,b)
# M 2
dis = np.linalg.norm(a-b)
dis

2.8284271247461903

In [17]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
#1.如何垂直堆叠两个数组?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# 三种方法
np.concatenate([a,b],axis = 0)
np.vstack([a,b])
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
#2.如何水平堆叠两个数组?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# 三种方法
np.concatenate([a,b],axis = 1)
np.hstack([a,b])
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [44]:
#3.如何没有硬编码的情况下，在numpy中如何生成自定义序列
# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [47]:
# 4.如何获得两个python numpy数组之间的共同元素?
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,10])
np.intersect1d(a,b)

array([5, 6])

In [48]:
# 5.从一个数组中删除存在于另一个数组中的元素
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9,10])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [52]:
#6.获取两个数组元素匹配的索引号
a = np.array([1,2,3,4,5,6])
b = np.array([5,2,7,8,5,6])
np.where(a == b)

(array([1, 4, 5]),)

In [69]:
#7.从numpy数组中提取给定范围内的所有数字
a = np.arange(15)
# M 1
index = np.where((a >= 5) & (a <= 10))
a[index]
# M 2
a = np.arange(15)
index = np.where(np.logical_and(a >= 5,a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
#8.如何将处理标量的python函数在numpy数组上运行
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx,otypes = [float])
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
pair_max(a,b)

array([5., 4., 3., 4., 5.])

In [80]:
#9.如何交换2维numpy数组中的两个列
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [84]:
#10.如何交换2维numpy数组中的两个行
arr = np.arange(9).reshape(3,3)
arr
arr[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [85]:
#11.如何反转2维数组的行
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [86]:
#12.如何反转二维数组的列
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [96]:
#13.如何创建一个包含5到10之间随机浮点数的二维数组
arr = np.arange(9).reshape(3,3)
# M 1
rand_arr = np.random.randint(low=5,high=10,size=(5,3)) + np.random.random((5,3))
rand_arr
# M 2
rand_arr = np.random.uniform(5,10,size = (5,3))
rand_arr

array([[6.38411285, 9.65893531, 7.40326103],
       [5.29170575, 9.89979702, 5.5855423 ],
       [9.71262855, 6.75392906, 8.9454541 ],
       [8.87312591, 9.24831227, 5.6628751 ],
       [8.36507115, 8.20616564, 8.004995  ]])

In [108]:
#14.打印python numpy数组并保留3位小数
rand_arr = np.random.random([5,3])
rand_arr
np.set_printoptions(precision=3)
rand_arr

array([[0.187, 0.689, 0.97 ],
       [0.273, 0.148, 0.947],
       [0.479, 0.64 , 0.055],
       [0.019, 0.857, 0.501],
       [0.07 , 0.996, 0.657]])

In [111]:
#15.如何在不截断的情况下打印完整的numpy数组
a = np.arange(15)
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
# 16.如何在python numpy中导入含有数字和文本的数据集，并保持的文本完整性
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',',dtype='object')
iris[:6]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa']], dtype=object)

In [117]:
# 17.如何从一维元组数组中提取特定的列
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_id = np.genfromtxt(url, delimiter=',',dtype=None)
sp = np.array([row[4] for row in iris_id])
sp[:3]

/home/mzl/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'], dtype='|S18')

In [119]:
# 18.如何计算numpy数组的平均值，中位数，标准差
a = np.array([1,2,3,4,5])
mu,med,sd = np.mean(a) , np.median(a) , np.std(a)
mu,med,sd

(3.0, 3.0, 1.4142135623730951)

In [129]:
#19.如何标准化一个数组至0到1之间
a = np.array([1,2,3,4,5])
smax ,smin = a.max(), a.min()
smax,smin
S = (a - smin) / (smax - smin)
S

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [130]:
#20.如何计算softmax值
a = np.array([1,2,3,4,5])
def softmax(x):
    ex = np.exp(x - np.max(x))
    return ex / ex.sum(axis = 0)
softmax(a)

array([0.012, 0.032, 0.086, 0.234, 0.636])

In [136]:
# 21.如何根据两个或多个条件过滤一个numpy数组？
a = np.arange(9).reshape(3,3)
b = (a[:,2] > 5) & (a[:,0] > 5)
a[b]

array([[6, 7, 8]])

In [137]:
#22.如何获得数组中第二大的元素值？
a = np.array([5,2,4,3,1])
np.unique(np.sort(a))[-2]

4

In [141]:
#23.如何在numpy数组中找到最频繁出现的值？
a = np.array([1,2,3,3,4])
vl,counts = np.unique(a, return_counts=True)
vl[np.argmax(counts)]
vl,counts

(array([1, 2, 3, 4]), array([1, 1, 2, 1]))

In [143]:
#24.如何将所有大于给定值的值替换为给定的cutoff值
a = np.array([1,2,3,4,5])
np.where(a < 3,3, np.where(a > 4,4,a))

array([3, 3, 3, 4, 4])

In [153]:
#25.如何将多维数组转换为平坦的一维数组？
a = np.arange(3)
b = np.arange(3,7)
c = np.arange(7,10)
d = np.array([a, b, c])
e = np.array([i for j in d for i in a])
e

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [158]:
#26.如何根据给定的分类变量创建分组ID？
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sp = np.genfromtxt(url, delimiter=',',dtype='str', usecols=4)
ss = np.sort(np.random.choice(sp, size=20))
output = [np.argwhere(np.unique(ss) == s).tolist()[0][0] for val in np.unique(ss) 
          for s in ss[ss == val]]
output

[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]

In [174]:
#27.如何找到numpy二维数组每一行中的最大值
a = np.random.randint(1,10,[5,3])
a
np.amax(a,axis = 1) # axis = 0 ：每一列的最大值

array([9, 9, 4, 9, 9])

In [210]:
#28.如何将PIL图像转换为numpy数组？
from io import BytesIO
from PIL import Image
import PIL ,requests
URL='https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
re = requests.get(URL)
I = Image.open(BytesIO(re.content))
#I = I.resize([150,150])
I = np.array(I)
#I
#I[...,::-1]
#I[:,[2,1,0]]
#im = PIL.Image.fromarray(np.uint8(I))
#Image.Image.show(im)


In [213]:
#sigmoid：
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def tanh(x):
    return 2 * sigmoid(2*x) - 1

def relu(x):
    return max(0,x)

def Leaky_Relu(x):
    a = 0.01 # a 取值一般为0.1或者0.01
    return max(a * x, x)

Leaky_Relu(-8)

-0.08