In [2]:
#计算两个数组之间的欧氏距离？
import numpy as np
a = np.array([1,2,3])
b = np.array([3,2,1])
# M 1
def Dis(a,b):
    dis = np.sqrt(np.sum(np.square(a - b)))
    return dis
Dis(a,b)
# M 2
dis = np.linalg.norm(a-b)
dis

2.8284271247461903

In [2]:
arr = np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
#交换2维numpy数组中的两个列
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]
#arr[[0,2,1],:] # 交换行

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [4]:
#反转2维数组的行
arr = np.arange(9).reshape(3,3)
arr[::-1]
arr[:,::-1] # 反转列

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [5]:
#在不截断的情况下打印完整的numpy数组
a = np.arange(15)
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#计算numpy数组的平均值，中位数，标准差
a = np.array([1,2,3,4,5])
mu,med,sd = np.mean(a) , np.median(a) , np.std(a)
mu,med,sd

(3.0, 3.0, 1.4142135623730951)

In [7]:
# 标准化一个数组至0到1之间
a = np.array([1,2,3,4,5])
smax ,smin = a.max(), a.min()
smax,smin
S = (a - smin) / (smax - smin)
S

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# 计算softmax值
a = np.array([1,2,3,4,5])
def softmax(x):
    ex = np.exp(x - np.max(x))
    return ex / ex.sum(axis = 0)
softmax(a)

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [9]:
#实现激活函数：
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

def tanh(x):
    return 2 * sigmoid(2*x) - 1

def relu(x):
    return max(0,x)

def Leaky_Relu(x):
    a = 0.01 # a 取值一般为0.1或者0.01
    return max(a * x, x)

Leaky_Relu(-8)

-0.08

In [3]:
#将PIL图像转换为numpy数组
from io import BytesIO
from PIL import Image
import PIL ,requests
URL='https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
re = requests.get(URL)
I = Image.open(BytesIO(re.content))
#I = I.resize([150,150])
I = np.array(I)
#I
# RGB to BGR
#I[...,::-1]

In [5]:
# eye函数，生成单位向量
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#创建零向量，zeros函数
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# arange函数，创建一个在给定范围的向量
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
# reshape函数，将array变形为矩阵
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#diag函数，diagonal对角线
np.diag([1,2,3,4],k=0) 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [13]:
#函数tile(A,reps),reps即重复的次数，不仅可以是数字，还可以是array
np.tile(np.array([[0,1],[0,1]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [14]:
#矩阵点乘
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [22]:
# x1第一个元素跟x2的每一个元素相乘作为第一行，x1第二个元素跟x2每一个元素相乘作为第二行....
np.outer(np.ones((5,3)),np.ones((3,2)))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
 # x1中的元素和x2中的元素一一对应相乘
a = [1,2,3]
b = [3,2,1]
np.multiply(a, b)

array([3, 4, 3])

In [16]:
# 矩阵相加，5*5矩阵+1*5的向量，相当于每一行都加上1*5矩阵
Z = np.zeros((5,5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [19]:
# plot()画出的图可以加上图名图例标题等
import numpy as np
import matplotlib.pyplot as plt
%matplotlib
x = np.arange(0,3*np.pi,0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x,y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

Using matplotlib backend: Qt5Agg


In [21]:
#图像转矢量
# 为了提高训练是的计算速度，
#一般会把图像转成矢量，一张三通道的图像的格式是(width,height,3)会转成(width∗height∗3,1)
def image2vector(image):
    v = image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))
    return v
image = np.array([[[0.67826139, 0.29380381],
                       [0.90714982, 0.52835647],
                       [0.4215251, 0.45017551]],

                      [[0.92814219, 0.96677647],
                       [0.85304703, 0.52351845],
                       [0.19981397, 0.27417313]],

                      [[0.60659855, 0.00533165],
                       [0.10820313, 0.49978937],
                       [0.34144279, 0.94630077]]])

image2vector(image)

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [27]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

# L1损失函数 :L2(ŷ ,y) = ∑|y(i)−ŷ (i)|
def L1(yhat, y):
    loss = np.sum(abs(y - yhat))
    return loss

L1(yhat, y)

1.1

In [28]:
# L2 损失函数: L2(ŷ ,y) = ∑ (y(i)−ŷ (i))2
def L2(yhat, y):
    loss = np.sum(np.multiply((y - yhat), (y - yhat)))
    return loss

L2(yhat, y)

0.43

In [29]:
# vstack是指沿着纵轴拼接两个array，vertical
# hstack是指沿着横轴拼接两个array，horizontal
a = np.arange(6).reshape((2, 3))
b = np.arange(6, 12).reshape((2, 3))
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])